version: '3'

services:
  nginx:
    image: nginx:latest
    environment:
      - MYSQL_DATABASE=cms
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=!OneTwo3
      - MYSQL_HOST=mysql
    ports:
      - "80:80"
    volumes:
      - .:/home/cms
      - ./container-build/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  php-cli:
    image: shaunfreeman/php:7.4-cli
    working_dir: /home/cms
    environment:
      - MYSQL_DATABASE=cms
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=!OneTwo3
      - MYSQL_HOST=mysql
      - PHP_IDE_CONFIG=serverName=my.local
    tty: true
    volumes:
      - .:/home/cms
    ports:
      - "9009:9009"
    depends_on:
      - mysql

  php-fpm:
    build:
      context: .
      dockerfile: container-build/php/fpm/Dockerfile
      args:
        uid: "${UID}"
        user: "${USER}"
    working_dir: /home/cms
    environment:
      - MYSQL_DATABASE=cms
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=!OneTwo3
      - MYSQL_HOST=mysql
    volumes:
      - .:/home/cms
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=!OneTwo3
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=!OneTwo3
      - MYSQL_DATABASE=cms
    volumes:
      - ./container-build/mysql/00-schema.sql:/docker-entrypoint-initdb.d/00-schma.sql
      - ./container-build/mysql/10-cms_users.sql:/docker-entrypoint-initdb.d/10-cms_users.sql
      - ./container-build/mysql/10-cms_managers.sql:/docker-entrypoint-initdb.d/10-cms_managers.sql
